// Generated by data binding compiler. Do not edit!
package com.evinurastina.foodapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;
import com.example.foodapp.R;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;
import java.lang.Deprecated;
import java.lang.Object;

public abstract class FragmentRecipeBinding extends ViewDataBinding {
  @NonNull
  public final TextView ingredientTitle;

  @NonNull
  public final TextView instructionTitle;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final ImageView recipeImage;

  @NonNull
  public final TextView recipeIngredient;

  @NonNull
  public final TextView recipeInstruction;

  @NonNull
  public final ScrollView recipeScrollView;

  @NonNull
  public final TextView recipeText;

  @NonNull
  public final TextView videoTitle;

  @NonNull
  public final YouTubePlayerView youtubePlayerView;

  protected FragmentRecipeBinding(Object _bindingComponent, View _root, int _localFieldCount,
      TextView ingredientTitle, TextView instructionTitle, ProgressBar progressBar,
      ImageView recipeImage, TextView recipeIngredient, TextView recipeInstruction,
      ScrollView recipeScrollView, TextView recipeText, TextView videoTitle,
      YouTubePlayerView youtubePlayerView) {
    super(_bindingComponent, _root, _localFieldCount);
    this.ingredientTitle = ingredientTitle;
    this.instructionTitle = instructionTitle;
    this.progressBar = progressBar;
    this.recipeImage = recipeImage;
    this.recipeIngredient = recipeIngredient;
    this.recipeInstruction = recipeInstruction;
    this.recipeScrollView = recipeScrollView;
    this.recipeText = recipeText;
    this.videoTitle = videoTitle;
    this.youtubePlayerView = youtubePlayerView;
  }

  @NonNull
  public static FragmentRecipeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot) {
    return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.fragment_recipe, root, attachToRoot, component)
   */
  @NonNull
  @Deprecated
  public static FragmentRecipeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable Object component) {
    return ViewDataBinding.<FragmentRecipeBinding>inflateInternal(inflater, R.layout.fragment_recipe, root, attachToRoot, component);
  }

  @NonNull
  public static FragmentRecipeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.fragment_recipe, null, false, component)
   */
  @NonNull
  @Deprecated
  public static FragmentRecipeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable Object component) {
    return ViewDataBinding.<FragmentRecipeBinding>inflateInternal(inflater, R.layout.fragment_recipe, null, false, component);
  }

  public static FragmentRecipeBinding bind(@NonNull View view) {
    return bind(view, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.bind(view, component)
   */
  @Deprecated
  public static FragmentRecipeBinding bind(@NonNull View view, @Nullable Object component) {
    return (FragmentRecipeBinding)bind(component, view, R.layout.fragment_recipe);
  }
}
