// Generated by data binding compiler. Do not edit!
package com.evinurastina.foodapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ProgressBar;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;
import androidx.recyclerview.widget.RecyclerView;
import com.example.foodapp.R;
import java.lang.Deprecated;
import java.lang.Object;

public abstract class FragmentAreaBinding extends ViewDataBinding {
  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final RecyclerView rvCategories;

  protected FragmentAreaBinding(Object _bindingComponent, View _root, int _localFieldCount,
      ProgressBar progressBar, RecyclerView rvCategories) {
    super(_bindingComponent, _root, _localFieldCount);
    this.progressBar = progressBar;
    this.rvCategories = rvCategories;
  }

  @NonNull
  public static FragmentAreaBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot) {
    return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.fragment_area, root, attachToRoot, component)
   */
  @NonNull
  @Deprecated
  public static FragmentAreaBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable Object component) {
    return ViewDataBinding.<FragmentAreaBinding>inflateInternal(inflater, R.layout.fragment_area, root, attachToRoot, component);
  }

  @NonNull
  public static FragmentAreaBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.fragment_area, null, false, component)
   */
  @NonNull
  @Deprecated
  public static FragmentAreaBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable Object component) {
    return ViewDataBinding.<FragmentAreaBinding>inflateInternal(inflater, R.layout.fragment_area, null, false, component);
  }

  public static FragmentAreaBinding bind(@NonNull View view) {
    return bind(view, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.bind(view, component)
   */
  @Deprecated
  public static FragmentAreaBinding bind(@NonNull View view, @Nullable Object component) {
    return (FragmentAreaBinding)bind(component, view, R.layout.fragment_area);
  }
}
